version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

    working_directory: ~/merchant-fe-doc/website

    steps:
      - checkout
      
      - run: git config --global user.email "ysyfff@users.noreply.github.com"

      - run: git config --global user.name "ysyfff"

      - run: echo "machine github.com login ysyfff password $GITHUB_TOKEN" > ~/.netrc

      - run: cd website && yarn install && GIT_USER=ysyfff yarn run publish-gh-pages

